# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get Pull Request
      run: |
          curl --fail --request GET https://api.github.com/repos/nguyensn29/GithubActionTest/pulls
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "${{ github.ref_name }}"
    - name: get Pull Request
      run: |
          curl --fail --request POST https://x-access-token:${{ secrets.TOKEN }}@api.github.com/repos/nguyensn29/GithubActionTest/pulls \
           -d '{"head":"nguyensn29-patch-9","base":"main", "title":"pull request for patch 9", "body:"pull request for patch 9"}' -H "Accept: application/vnd.github.v3+json" 
